name: dart_slimlib
description: Interop package for Easyling's Slimlib
version: 0.1.3
author: Daniel Varga-Hali <dvarga@skawa.hu>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  js: ^0.6.0
dev_dependencies:
  test: ^1.14.2
